// Tour steps. Every preview here is byte-identical to what
// `circ-compile <step.circ> --preview --color=never` produces on the current
// compiler — generated by `scripts/compile-content.ts` (run after rebuilding
// the binary with `zig build circ-compile`).

export interface TourStep {
  title: string;
  prose: string;
  source: string;
  preview: string;
}

export const tour: TourStep[] = [
  {
    title: 'A single NOT gate',
    prose:
      "The smallest possible circuit. One input pin `a`, one inverter, one output pin. " +
      "Every program is a flat list of declarations: name a thing, then wire its ports. " +
      "The `.out` suffix on a primitive's instance name is its single implicit output port.",
    source: `input a
not n(in=a)
output out(in=n.out)
`,
    preview: `╭───╮     ╭───╮     ╭─────╮
│ a ├○───▶┤NOT├○───▶┤ out │
╰───╯     ╰───╯     ╰─────╯`,
  },
  {
    title: 'AND of two inputs',
    prose:
      "Two inputs, named `a` and `b`, feed an AND gate. The gate has two input ports — " +
      "`a` and `b` — that you bind by name in the parenthesised list. The output of the " +
      "gate goes to a single output pin named `out`.",
    source: `input a, b
and g(a=a, b=b)
output out(in=g.out)
`,
    preview: `╭───╮     ╭───╮
│ a ├○───▶┤   │     ╭─────╮
╰───╯     │AND├○───▶┤ out │
      ╭──▶┤   │     ╰─────╯
╭───╮ │   ╰───╯
│ b ├○╯
╰───╯`,
  },
  {
    title: 'Naming an intermediate signal',
    prose:
      "A `wire` is a one-port pass-through: the value on `in` is, after evaluation, " +
      "exactly the value on `out`. It exists so you can give a derived signal a name. " +
      "Without `clock_buf` here, `gate.a` would be wired directly to `clk` — same logic, " +
      "less self-documenting.",
    source: `input clk, data
wire clock_buf(in=clk)
and gate(a=clock_buf.out, b=data)
output out(in=gate.out)
`,
    preview: `╭─────╮      ╭───╮
│ clk ├○────▶┤   │     ╭─────╮
╰─────╯      │AND├○───▶┤ out │
         ╭──▶┤   │     ╰─────╯
╭──────╮ │   ╰───╯
│ data ├○╯
╰──────╯`,
  },
  {
    title: 'Anonymous nested components',
    prose:
      "A component can be instantiated inline as the value of a port. The inverter " +
      "here has no instance name; its `.out` is wired immediately into `gate1`'s `b` " +
      "port. The same wiring rules apply — anonymous nesting is just syntactic sugar " +
      "for declaring an unnamed component.",
    source: `input a
input b
and gate1(a=a, b=not(in=b).out)
output out(in=gate1.out)
`,
    preview: `╭───╮               ╭───╮
│ a ├○─────────────▶┤   │     ╭─────╮
╰───╯               │AND├○───▶┤ out │
                ╭──▶┤   │     ╰─────╯
╭───╮     ╭───╮ │   ╰───╯
│ b ├○───▶┤NOT├○╯
╰───╯     ╰───╯`,
  },
  {
    title: 'A half-adder',
    prose:
      "Two single-bit numbers `a` and `b` sum to `(carry, sum)` where `sum = a XOR b` " +
      "and `carry = a AND b`. The `xor` keyword is a built-in macro that expands to " +
      "primitives at compile time. A single file may use a macro with no `import` line at all; " +
      "the explicit form shown here still works. This is the classic Nand2Tetris milestone.",
    source: `// half_adder.circ
import xor "<builtin>/xor.circ"
input a, b
xor s(a=a, b=b)
and c(a=a, b=b)
output sum(in=s.out)
output carry(in=c.out)
`,
    preview: `╭───╮     ╭───╮
│ a ├○●──▶┤   │         ╭───────╮
╰───╯ │   │AND├○───────▶┤ carry │
      │╭─▶┤   │         ╰───────╯
╭───╮ ││  ╰───╯
│ b ├○┼╯
╰───╯ ││  ╭───────╮
      ╰┼─▶┤       │     ╭─────╮
       │  │[xor:s]├○───▶┤ sum │
       ╰─▶┤       │     ╰─────╯
          ╰───────╯`,
  },
  {
    title: 'A full-adder, by importing the half-adder',
    prose:
      "Imports glue files together. The root file declares a `half_adder` alias and " +
      "uses it twice — once for the low-bit sum, once to fold in the carry-in. The " +
      "carry-out is the OR of the two intermediate carries. The half-adder's ports " +
      "(`a`, `b`, `sum`, `carry`) are exactly its `input` and `output` declarations. " +
      "Notice in the preview how the half-adders show up as `[half_adder:ha1]` and " +
      "`[half_adder:ha2]` boxes — opaque sub-circuits, just like the built-in macros.",
    source: `// half_adder.circ
import xor "<builtin>/xor.circ"
input a, b
xor s(a=a, b=b)
and c(a=a, b=b)
output sum(in=s.out)
output carry(in=c.out)

// root.circ
import half_adder "half_adder.circ"
input a, b, cin
half_adder ha1(a=a, b=b)
half_adder ha2(a=ha1.sum, b=cin)
or cout_or(a=ha1.carry, b=ha2.carry)
output sum(in=ha2.sum)
output cout(in=cout_or.out)
`,
    preview: `╭───╮       ╭────────────────╮
│ a ├○─────▶┤                │                            ╭────────────╮
╰───╯       │[half_adder:ha1]├○●─────────────────────────▶┤            │     ╭──────╮
        ╭──▶┤                │ │   ╭────────────────╮     │[or:cout_or]├○───▶┤ cout │
╭───╮   │   ╰────────────────╯ ╰──▶┤                │ ╭──▶┤            │     ╰──────╯
│ b ├○──╯                          │[half_adder:ha2]├○╮   ╰────────────╯
╰───╯                          ╭──▶┤                │ │                      ╭─────╮
                               │   ╰────────────────╯ ╰─────────────────────▶┤ sum │
╭─────╮                        │                                             ╰─────╯
│ cin ├○───────────────────────╯
╰─────╯`,
  },
  {
    title: 'Stable feedback through wires',
    prose:
      "Combinational feedback is rejected at compile time — a chain of gates whose " +
      "output drives its own input is a hard error (`E008`). But the validator looks at " +
      "the signal graph, not the textual order, and a loop that passes through a gate is " +
      "sequential logic, not a combinational loop. Here two `not` gates connect end to end " +
      "through two `wire` pass-throughs: the ring closes, but the NOT gates break it, so it " +
      "compiles cleanly. This is the substrate the language gives you for building " +
      "latches and other feedback structures.",
    source: `not n1(in=w2.out)
wire w1(in=n1.out)
not n2(in=w1.out)
wire w2(in=n2.out)
`,
    preview: `      ╭───╮     ╭───╮
  ╭──▶┤NOT├○───▶┤NOT├○╮
  │   ╰───╯     ╰───╯ │
  ╰───────────────────╯`,
  },
];
