//! Byte-exact goldens for the `--analyze` JSON that `circ-lsp` and the
//! playground consume. Each case mirrors one of the in-memory overlays used
//! by the inline tests in `lib/analyze/analyze.zig`; the expected files under
//! `tests/fixtures/expected-analyze/` were generated by the Go-backed parser
//! and are the contract a replacement parser must reproduce unchanged.
//!
//! The overlay paths never exist on disk, so `file_loader` keeps the given
//! key as the file path and the goldens are machine-independent.
const std = @import("std");
const analyze = @import("analyze");
const golden = @import("golden");

const Case = struct {
    name: []const u8,
    overlay_path: []const u8,
    source: []const u8,
    expected_json_path: []const u8,
};

const cases = [_]Case{
    .{
        .name = "clean",
        .overlay_path = "/virtual/clean.circ",
        .source = "input a\ninput b\nand g(a=a, b=b)\noutput out(in=g.out)\n",
        .expected_json_path = "tests/fixtures/expected-analyze/clean.json",
    },
    .{
        .name = "truncated",
        .overlay_path = "/virtual/truncated.circ",
        .source = "input a\nand g(a=\n",
        .expected_json_path = "tests/fixtures/expected-analyze/truncated.json",
    },
    .{
        .name = "junk_line",
        .overlay_path = "/virtual/junk_line.circ",
        .source = "input a\n%%% junk %%%\nand g(a=a, b=a)\noutput o(in=g.out)\n",
        .expected_json_path = "tests/fixtures/expected-analyze/junk_line.json",
    },
    .{
        .name = "empty",
        .overlay_path = "/virtual/empty.circ",
        .source = "",
        .expected_json_path = "tests/fixtures/expected-analyze/empty.json",
    },
};

test "analyze json goldens for the lsp overlays" {
    for (cases) |case| {
        var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
        defer arena.deinit();
        const a = arena.allocator();

        var overlay = analyze.Overlay{};
        try overlay.put(a, case.overlay_path, case.source);
        const result = try analyze.analyze(a, case.overlay_path, overlay);

        var out: std.ArrayList(u8) = .{};
        try analyze.renderJson(out.writer(a), result);

        golden.expectGolden(out.items, case.expected_json_path) catch |err| {
            std.debug.print("Analyze golden failed: {s}\n", .{case.name});
            return err;
        };
    }
}
