//! Generated by circ-compile. Do not edit.
//! Source: "empty_ish.circ"
//! Compiled at: "2026-05-01T22:00:00Z"
//! Compiler version: "circ-compiler/dev"

const std = @import("std");
const engine = @import("circuit.zig");

fn buildCircuit(circuit: *engine.Circuit) !struct {
    input_a: *engine.Component,
    output_out: *engine.Component,
} {
    const comp_a_0 = try circuit.createComponent(.{ .input_pin_gate = .{} }, 1);
    const comp_out_1 = try circuit.createComponent(.{ .output_pin = .{} }, 1);
    try circuit.connect(comp_a_0.port("out"), comp_out_1.port("in"));
    return .{
        .input_a = comp_a_0,
        .output_out = comp_out_1,
    };
}

const file_info_blob: []const u8 = &.{
    1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    14, 0, 0, 0, 101, 109, 112, 116, 121, 95, 105, 115, 104, 46, 99, 105,
    114, 99, 20, 0, 0, 0, 50, 48, 50, 54, 45, 48, 53, 45, 48, 49,
    84, 50, 50, 58, 48, 48, 58, 48, 48, 90, 17, 0, 0, 0, 99, 105,
    114, 99, 45, 99, 111, 109, 112, 105, 108, 101, 114, 47, 100, 101, 118, 1,
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 97, 1, 0, 0, 0,
    0, 0, 0, 0, 3, 0, 0, 0, 111, 117, 116,
};

const DebugPath = struct {
    component_id: u32,
    segments: []const []const u8,
};
const debug_paths: []const DebugPath = &.{
    .{ .component_id = 0, .segments = &.{ "empty_ish.circ", "a" } },
    .{ .component_id = 1, .segments = &.{ "empty_ish.circ", "out" } },
};

const topology_blob: []const u8 = "circ.topology.v0.min";

const PtrLen = extern struct { ptr: ?[*]const u8, len: usize };
const expected_component_count: usize = 2;
const input_component_ids: []const u32 = &.{
    0,
};
const output_component_ids: []const u32 = &.{
    0,
};
var gpa = std.heap.wasm_allocator;
var runtime_initialized: bool = false;
var runtime_circuit: engine.Circuit = undefined;
var component_table: []const *engine.Component = &.{};

fn emptyPtrLen() PtrLen {
    return .{ .ptr = null, .len = 0 };
}

fn containsId(list: []const u32, id: u32) bool {
    for (list) |candidate| {
        if (candidate == id) return true;
    }
    return false;
}

fn bufferFromStaticBytes(bytes: []const u8) PtrLen {
    if (bytes.len == 0) return emptyPtrLen();
    const buffer = gpa.alloc(u8, bytes.len) catch return emptyPtrLen();
    std.mem.copyForwards(u8, buffer, bytes);
    return .{ .ptr = buffer.ptr, .len = buffer.len };
}

export fn init() void {
    if (runtime_initialized) return;
    runtime_circuit = engine.Circuit.init() catch return;
    _ = buildCircuit(&runtime_circuit) catch {
        runtime_circuit.deinit();
        return;
    };
    component_table = runtime_circuit.nodes.items;
    if (component_table.len != expected_component_count) {
        runtime_circuit.deinit();
        component_table = &.{};
        return;
    }
    runtime_initialized = true;
}

export fn deinit() void {
    if (!runtime_initialized) return;
    runtime_circuit.deinit();
    component_table = &.{};
    runtime_initialized = false;
}

export fn reset() void {
    if (runtime_initialized) deinit();
    init();
}

export fn run() void {
    if (!runtime_initialized) return;
    runtime_circuit.propagate() catch return;
}

export fn stop() void {
    // v0 no-op; retained for forward-compatible runtime API shape.
}

export fn setPin(component_id: i32, value: i64, defined: i64) void {
    if (!runtime_initialized) return;
    if (component_id < 0) return;
    const id: u32 = @intCast(component_id);
    if (id >= component_table.len) return;
    if (!containsId(input_component_ids, id)) return;
    const comp = component_table[id];
    const width = comp.state_handle.tier;
    const state = engine.BitVecState.fromRaw(@bitCast(value), @bitCast(defined), width);
    runtime_circuit.propagateEvent(comp, state) catch return;
}

export fn getOutputState(component_id: i32) i32 {
    if (!runtime_initialized) return 2;
    if (component_id < 0) return 2;
    const id: u32 = @intCast(component_id);
    if (id >= component_table.len) return 2;
    if (!containsId(output_component_ids, id)) return 2;
    return runtime_circuit.readState(component_table[id].state_handle).toInt();
}

export fn getStateSnapshot() callconv(.c) PtrLen {
    if (!runtime_initialized) return emptyPtrLen();
    const encoded = runtime_circuit.encodeState() catch return emptyPtrLen();
    return .{ .ptr = encoded.ptr, .len = encoded.len };
}

export fn getTopology() callconv(.c) PtrLen {
    return bufferFromStaticBytes(topology_blob);
}

export fn getPendingEvents() callconv(.c) PtrLen {
    const empty_pending: []const u8 = &.{};
    return bufferFromStaticBytes(empty_pending);
}

export fn getFileInfo() callconv(.c) PtrLen {
    return .{ .ptr = file_info_blob.ptr, .len = file_info_blob.len };
}

export fn freeBuffer(ptr: ?[*]const u8, len: usize) void {
    if (len == 0) return;
    const non_null = ptr orelse return;
    const mutable: [*]u8 = @constCast(non_null);
    gpa.free(mutable[0..len]);
}
