Program     <- (Annotation / ImportDecl / Declaration / Connection)*
Annotation  <- '//' (![\n] .)*

ImportDecl  <- 'import' Identifier '"' (!["] .)* '"'

Declaration <- (ComponentType Identifier BusType) / (ComponentType IdentList)
AnonDecl    <- (ComponentType BusType)
ComponentType    <- 'input' / 'output' / 'bus' / 'led' / 'and' / 'or' / 'not' / 'xor' / 'nand' / Identifier
Identifier  <- [a-zA-Z_][a-zA-Z0-9_]*
PortRef     <- (AnonDecl '.' Identifier) / (Identifier ('.' Identifier)?)
IdentList   <- Identifier (',' Identifier)*
BusType     <- '(' Identifier '=' PortRef (',' Identifier '=' PortRef)* ')'

Connection  <- PortRef '<>' PortRef