//! Generated by circ-compile. Do not edit.
//! Source: "root.circ"
//! Compiled at: "2026-05-01T22:00:00Z"
//! Compiler version: "circ-renderer-z/dev"

const std = @import("std");
const engine = @import("circuit.zig");

fn buildFile_0(circuit: *engine.Circuit) !struct {
    input_a: *engine.Component,
    output_out: *engine.Component,
} {
    const comp_a_0 = try circuit.createComponent(.{ .input_pin_gate = .{} });
    const inst_u_1 = try buildFile_1(circuit);
    const comp_out_2 = try circuit.createComponent(.{ .output_pin = .{} });
    try circuit.connect(comp_a_0.port("out"), inst_u_1.input_rin.port("in"));
    try circuit.connect(inst_u_1.output_rout.port("out"), comp_out_2.port("in"));
    return .{
        .input_a = comp_a_0,
        .output_out = comp_out_2,
    };
}

fn buildFile_1(circuit: *engine.Circuit) !struct {
    input_rin: *engine.Component,
    output_rout: *engine.Component,
} {
    const comp_rin_0 = try circuit.createComponent(.{ .input_pin_gate = .{} });
    const inst_u_1 = try buildFile_2(circuit);
    const comp_rout_2 = try circuit.createComponent(.{ .output_pin = .{} });
    try circuit.connect(comp_rin_0.port("out"), inst_u_1.input_tin.port("in"));
    try circuit.connect(inst_u_1.output_tout.port("out"), comp_rout_2.port("in"));
    return .{
        .input_rin = comp_rin_0,
        .output_rout = comp_rout_2,
    };
}

fn buildFile_2(circuit: *engine.Circuit) !struct {
    input_tin: *engine.Component,
    output_tout: *engine.Component,
} {
    const comp_tin_0 = try circuit.createComponent(.{ .input_pin_gate = .{} });
    const inst_u_1 = try buildFile_3(circuit);
    const comp_tout_2 = try circuit.createComponent(.{ .output_pin = .{} });
    try circuit.connect(comp_tin_0.port("out"), inst_u_1.input_din.port("in"));
    try circuit.connect(inst_u_1.output_dout.port("out"), comp_tout_2.port("in"));
    return .{
        .input_tin = comp_tin_0,
        .output_tout = comp_tout_2,
    };
}

fn buildFile_3(circuit: *engine.Circuit) !struct {
    input_din: *engine.Component,
    output_dout: *engine.Component,
} {
    const comp_din_0 = try circuit.createComponent(.{ .input_pin_gate = .{} });
    const inst_u_1 = try buildFile_4(circuit);
    const comp_dout_2 = try circuit.createComponent(.{ .output_pin = .{} });
    try circuit.connect(comp_din_0.port("out"), inst_u_1.input_cin.port("in"));
    try circuit.connect(inst_u_1.output_cout.port("out"), comp_dout_2.port("in"));
    return .{
        .input_din = comp_din_0,
        .output_dout = comp_dout_2,
    };
}

fn buildFile_4(circuit: *engine.Circuit) !struct {
    input_cin: *engine.Component,
    output_cout: *engine.Component,
} {
    const comp_cin_0 = try circuit.createComponent(.{ .input_pin_gate = .{} });
    const comp_cout_1 = try circuit.createComponent(.{ .output_pin = .{} });
    try circuit.connect(comp_cin_0.port("out"), comp_cout_1.port("in"));
    return .{
        .input_cin = comp_cin_0,
        .output_cout = comp_cout_1,
    };
}

const file_info_blob: []const u8 = &.{
    1, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 9, 0, 0, 0,
    9, 0, 0, 0, 114, 111, 111, 116, 46, 99, 105, 114, 99, 20, 0, 0,
    0, 50, 48, 50, 54, 45, 48, 53, 45, 48, 49, 84, 50, 50, 58, 48,
    48, 58, 48, 48, 90, 19, 0, 0, 0, 99, 105, 114, 99, 45, 114, 101,
    110, 100, 101, 114, 101, 114, 45, 122, 47, 100, 101, 118, 1, 0, 0, 0,
    0, 0, 0, 0, 1, 0, 0, 0, 97, 1, 0, 0, 0, 9, 0, 0,
    0, 3, 0, 0, 0, 111, 117, 116,
};

const SubCircuit = struct {
    instance_path: []const []const u8,
    target_file_id: u32,
};
const sub_circuits: []const SubCircuit = &.{
    .{ .instance_path = &.{ "root.circ", "u" }, .target_file_id = 1 },
    .{ .instance_path = &.{ "root.circ", "u", "u" }, .target_file_id = 2 },
    .{ .instance_path = &.{ "root.circ", "u", "u", "u" }, .target_file_id = 3 },
    .{ .instance_path = &.{ "root.circ", "u", "u", "u", "u" }, .target_file_id = 4 },
};

const DebugPath = struct {
    component_id: u32,
    segments: []const []const u8,
};
const debug_paths: []const DebugPath = &.{
    .{ .component_id = 0, .segments = &.{ "root.circ", "a" } },
    .{ .component_id = 1, .segments = &.{ "root.circ", "u", "rin" } },
    .{ .component_id = 2, .segments = &.{ "root.circ", "u", "u", "tin" } },
    .{ .component_id = 3, .segments = &.{ "root.circ", "u", "u", "u", "din" } },
    .{ .component_id = 4, .segments = &.{ "root.circ", "u", "u", "u", "u", "cin" } },
    .{ .component_id = 5, .segments = &.{ "root.circ", "u", "u", "u", "u", "cout" } },
    .{ .component_id = 6, .segments = &.{ "root.circ", "u", "u", "u", "dout" } },
    .{ .component_id = 7, .segments = &.{ "root.circ", "u", "u", "tout" } },
    .{ .component_id = 8, .segments = &.{ "root.circ", "u", "rout" } },
    .{ .component_id = 9, .segments = &.{ "root.circ", "out" } },
};

const topology_blob: []const u8 = "debug-paths-v1";

const PtrLen = extern struct { ptr: ?[*]const u8, len: usize };
const expected_component_count: usize = 10;
const input_component_ids: []const u32 = &.{
    0,
};
const output_component_ids: []const u32 = &.{
    9,
};
var gpa = std.heap.wasm_allocator;
var runtime_initialized: bool = false;
var runtime_circuit: engine.Circuit = undefined;
var component_table: []const *engine.Component = &.{};

fn emptyPtrLen() PtrLen {
    return .{ .ptr = null, .len = 0 };
}

fn containsId(list: []const u32, id: u32) bool {
    for (list) |candidate| {
        if (candidate == id) return true;
    }
    return false;
}

fn bufferFromStaticBytes(bytes: []const u8) PtrLen {
    if (bytes.len == 0) return emptyPtrLen();
    const buffer = gpa.alloc(u8, bytes.len) catch return emptyPtrLen();
    std.mem.copyForwards(u8, buffer, bytes);
    return .{ .ptr = buffer.ptr, .len = buffer.len };
}

fn buildRoot(circuit: *engine.Circuit) !void {
    _ = try buildFile_0(circuit);
}

export fn init() void {
    if (runtime_initialized) return;
    runtime_circuit = engine.Circuit.init() catch return;
    buildRoot(&runtime_circuit) catch {
        runtime_circuit.deinit();
        return;
    };
    component_table = runtime_circuit.nodes.items;
    if (component_table.len != expected_component_count) {
        runtime_circuit.deinit();
        component_table = &.{};
        return;
    }
    runtime_initialized = true;
}

export fn deinit() void {
    if (!runtime_initialized) return;
    runtime_circuit.deinit();
    component_table = &.{};
    runtime_initialized = false;
}

export fn reset() void {
    if (runtime_initialized) deinit();
    init();
}

export fn run() void {
    if (!runtime_initialized) return;
    runtime_circuit.propagate() catch return;
}

export fn stop() void {
    // v0 no-op; retained for forward-compatible runtime API shape.
}

export fn setPin(component_id: i32, state: i32) void {
    if (!runtime_initialized) return;
    if (component_id < 0) return;
    const id: u32 = @intCast(component_id);
    if (id >= component_table.len) return;
    if (!containsId(input_component_ids, id)) return;
    runtime_circuit.propagateEvent(component_table[id], engine.State.fromInt(state)) catch return;
}

export fn getOutputState(component_id: i32) i32 {
    if (!runtime_initialized) return 2;
    if (component_id < 0) return 2;
    const id: u32 = @intCast(component_id);
    if (id >= component_table.len) return 2;
    if (!containsId(output_component_ids, id)) return 2;
    return engine.State.toInt(component_table[id].output_state);
}

export fn getStateSnapshot() callconv(.c) PtrLen {
    if (!runtime_initialized) return emptyPtrLen();
    const encoded = runtime_circuit.encodeState() catch return emptyPtrLen();
    return .{ .ptr = encoded.ptr, .len = encoded.len };
}

export fn getTopology() callconv(.c) PtrLen {
    return bufferFromStaticBytes(topology_blob);
}

export fn getPendingEvents() callconv(.c) PtrLen {
    const empty_pending: []const u8 = &.{};
    return bufferFromStaticBytes(empty_pending);
}

export fn getFileInfo() callconv(.c) PtrLen {
    return .{ .ptr = file_info_blob.ptr, .len = file_info_blob.len };
}

export fn freeBuffer(ptr: ?[*]const u8, len: usize) void {
    if (len == 0) return;
    const non_null = ptr orelse return;
    const mutable: [*]u8 = @constCast(non_null);
    gpa.free(mutable[0..len]);
}
