import type { PlaygroundController, ToolDescriptor } from '../playground-contract.ts';
const string = { type: 'string' } as const;
const number = { type: 'number' } as const;
export const exportSourceDescriptor: ToolDescriptor = { name: 'circ_export_source', description: 'Page a revision-bound source snapshot; source exports never include images or live state.', readOnly: true, inputSchema: { type: 'object', properties: { projectId: string, expectedSourceRevision: string, expectedTargetEpoch: string, format: string, cursor: string, maxCodeUnits: number }, required: ['projectId', 'expectedSourceRevision', 'expectedTargetEpoch'], additionalProperties: false } };
export const createShareLinkDescriptor: ToolDescriptor = { name: 'circ_create_share_link', description: 'Create a source-only fragment URL without clipboard or share-sheet APIs.', readOnly: true, inputSchema: { type: 'object', properties: { projectId: string, expectedSourceRevision: string, expectedTargetEpoch: string }, required: ['projectId', 'expectedSourceRevision', 'expectedTargetEpoch'], additionalProperties: false } };
export const downloadArtifactDescriptor: ToolDescriptor = { name: 'circ_download_artifact', description: 'Dispatch one copied WASM download and report only dispatch, never disk completion.', readOnly: false, inputSchema: { type: 'object', properties: { expectedArtifactId: string }, required: ['expectedArtifactId'], additionalProperties: false } };
export const downloadMemoryDescriptor: ToolDescriptor = { name: 'circ_download_memory', description: 'Dispatch one copied root-live or source-ROM raw binary image download.', readOnly: false, inputSchema: { type: 'object', properties: { source: string, projectId: string, expectedTargetEpoch: string, expectedArtifactId: string, expectedSessionId: string, expectedLiveStateRevision: string, expectedSourceRevision: string, expectedImageRevision: string, file: string, declaration: string, memory: string }, required: ['source', 'projectId'], additionalProperties: false } };
export const getTranscriptDescriptor: ToolDescriptor = { name: 'circ_get_transcript', description: 'Read immutable bounded log or replay-script transcript lines without opening or clearing the console.', readOnly: true, inputSchema: { type: 'object', properties: { format: string, cursor: string, limit: number }, required: ['format'], additionalProperties: false } };
export function exportHandlers(controller: PlaygroundController) { return { source: (input: Record<string, unknown>) => controller.exportSource(input as Parameters<PlaygroundController['exportSource']>[0]), share: (input: Record<string, unknown>) => controller.createShareLink(input as Parameters<PlaygroundController['createShareLink']>[0]), artifact: (input: Record<string, unknown>) => controller.downloadArtifact(input as Parameters<PlaygroundController['downloadArtifact']>[0]), memory: (input: Record<string, unknown>) => controller.downloadMemory(input as Parameters<PlaygroundController['downloadMemory']>[0]), transcript: (input: Record<string, unknown>) => controller.getTranscript(input as Parameters<PlaygroundController['getTranscript']>[0]) }; }
