import type { PlaygroundController, ToolDescriptor } from '../playground-contract.ts';
const string = { type: 'string' } as const;
const number = { type: 'number' } as const;
export const requestSchematicDescriptor: ToolDescriptor = { name: 'circ_request_schematic', description: 'Start, join, or reuse a preview operation with explicit current preview settings.', readOnly: false, inputSchema: { type: 'object', properties: { projectId: string, expectedSourceRevision: string, expectedTargetEpoch: string, expectedPreviewOptionsRevision: string }, required: ['projectId', 'expectedSourceRevision', 'expectedTargetEpoch', 'expectedPreviewOptionsRevision'], additionalProperties: false } };
export const getSchematicDescriptor: ToolDescriptor = { name: 'circ_get_schematic', description: 'Read one Unicode-safe page from a retained schematic operation.', readOnly: true, inputSchema: { type: 'object', properties: { operationId: string, cursor: string, maxCodeUnits: number }, required: ['operationId'], additionalProperties: false } };
export const getTopologyDescriptor: ToolDescriptor = { name: 'circ_get_topology', description: 'Read bounded structured full-topology components or connections from an exact artifact.', readOnly: true, inputSchema: { type: 'object', properties: { expectedArtifactId: string, section: string, scope: string, cursor: string, limit: number }, required: ['expectedArtifactId', 'section'], additionalProperties: false } };
export const requestTruthTableDescriptor: ToolDescriptor = { name: 'circ_request_truth_table', description: 'Start, join, or reuse a bounded exhaustive or live-pin-filtered Truth operation.', readOnly: false, inputSchema: { type: 'object', properties: { projectId: string, expectedSourceRevision: string, expectedTargetEpoch: string, expectedTruthOptionsRevision: string, expectedImageRevision: string, expectedArtifactId: string, expectedSessionId: string, expectedLiveStateRevision: string }, required: ['projectId', 'expectedSourceRevision', 'expectedTargetEpoch', 'expectedTruthOptionsRevision', 'expectedImageRevision'], additionalProperties: false } };
export const getTruthTableDescriptor: ToolDescriptor = { name: 'circ_get_truth_table', description: 'Read retained Truth rows without starting further enumeration.', readOnly: true, inputSchema: { type: 'object', properties: { operationId: string, cursor: string, limit: number }, required: ['operationId'], additionalProperties: false } };
export function inspectionHandlers(controller: PlaygroundController) { return { requestSchematic: (input: Record<string, unknown>) => controller.requestSchematic(input as Parameters<PlaygroundController['requestSchematic']>[0]), getSchematic: (input: Record<string, unknown>) => controller.getSchematic(input as Parameters<PlaygroundController['getSchematic']>[0]), getTopology: (input: Record<string, unknown>) => controller.getTopology(input as Parameters<PlaygroundController['getTopology']>[0]), requestTruth: (input: Record<string, unknown>) => controller.requestTruthTable(input as Parameters<PlaygroundController['requestTruthTable']>[0]), getTruth: (input: Record<string, unknown>) => controller.getTruthTable(input as Parameters<PlaygroundController['getTruthTable']>[0]) }; }
