const std = @import("std");
const ir = @import("ir_types");
const build_fn = @import("emit_build_fn");
const file_info = @import("emit_file_info");
const debug_paths = @import("emit_debug_paths");
const runtime = @import("emit_runtime");
const Writer = @import("emit_writer").Writer;

pub const EmitOptions = struct {
    source_name: []const u8,
    compile_timestamp: []const u8,
    compiler_version: []const u8,
};

pub fn emitModuleSource(allocator: std.mem.Allocator, module: *const ir.Module, options: EmitOptions) ![]u8 {
    var writer = Writer.init(allocator);
    defer writer.deinit();

    const source_name_lit = try writer.zigStringLiteral(options.source_name);
    defer allocator.free(source_name_lit);
    const timestamp_lit = try writer.zigStringLiteral(options.compile_timestamp);
    defer allocator.free(timestamp_lit);
    const compiler_version_lit = try writer.zigStringLiteral(options.compiler_version);
    defer allocator.free(compiler_version_lit);

    try writer.writeLine("//! Generated by circ-compile. Do not edit.");
    try writer.writeLineFmt("//! Source: {s}", .{source_name_lit});
    try writer.writeLineFmt("//! Compiled at: {s}", .{timestamp_lit});
    try writer.writeLineFmt("//! Compiler version: {s}", .{compiler_version_lit});
    try writer.writeLine("");
    try writer.writeLine("const std = @import(\"std\");");
    try writer.writeLine("const engine = @import(\"circuit.zig\");");
    try writer.writeLine("");

    const build_fn_snippet = try build_fn.emitBuildFunction(allocator, module);
    defer allocator.free(build_fn_snippet);
    try writer.writeRaw(build_fn_snippet);
    try writer.writeLine("");

    const file_info_snippet = try file_info.emitFileInfoConstants(allocator, module, .{
        .source_name = options.source_name,
        .compile_timestamp = options.compile_timestamp,
        .compiler_version = options.compiler_version,
    });
    defer allocator.free(file_info_snippet);
    try writer.writeRaw(file_info_snippet);
    try writer.writeLine("");

    const debug_paths_snippet = try debug_paths.emitDebugPathsConstants(allocator, module, .{
        .root_name = options.source_name,
    });
    defer allocator.free(debug_paths_snippet);
    try writer.writeRaw(debug_paths_snippet);
    try writer.writeLine("");
    try writer.writeLine("const topology_blob: []const u8 = \"debug-paths-v1\";");
    try writer.writeLine("");

    const runtime_snippet = try runtime.emitRuntimeExports(allocator, module);
    defer allocator.free(runtime_snippet);
    try writer.writeRaw(runtime_snippet);

    return writer.toOwnedSlice();
}
